export const appName = 'Public Watch'
export const appDescription = 'Public Database to track Politicians charged with Corruption'
export const host = 'https://publicwatchke.vercel.app'
export const maxCharsDescription: number = 1000

export const kenyanPoliticalParties = [
  'Kenya Kwanza',
  'Kenya African Democratic Union',
  'Kenya African National Union',
  'National Rainbow Coalition',
  'Orange Democratic Movement',
  'Party of National Unity',
  'Jubilee Party',
  'Kenya People\'s Union',
  'United Democratic Alliance',
  'Ford-Kenya',
  'Ford-People',
  'Social Democratic Party',
  'Amani National Congress',
]

export const counties = [
  'Kilifi',
  'Mombasa',
  'Kwale',
  'Tana River',
  'Lamu',
  'Taita Taveta',
  'Garissa',
  'Wajir',
  'Mandera',
  'Marsabit',
  'Isiolo',
  'Meru',
  'Embu',
  'Tharaka Nithi',
  'Laikipia',
  'Nyandarua',
  'Nyeri',
  'Kirinyaga',
  'Muranga',
  'Machakos',
  'Nakuru',
  'Narok',
  'Kajiado',
  'West Pokot',
  'Samburu',
  'Trans Nzoia',
  'Uasin Gishu',
  'Elgeyo Marakwet',
  'Nandi',
  'Bomet',
  'Kericho',
  'Baringo',
  'Vihiga',
  'Bungoma',
  'Kakamega',
  'Kisumu',
  'Siaya',
  'HomaBay',
  'Migori',
  'Kisii',
  'Nyamira',
  'Trans Mara',
  'Narok South',
  'Kwale North',
  'Nairobi',
]
